{{- if .Values.demoCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialsSecretName }}
  namespace: {{ include "weblogic-demo.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/part-of: weblogic-demo
type: Opaque
stringData:
  username: {{ .Values.demoCredentials.username | quote }}
  password: {{ .Values.demoCredentials.password | quote }}
{{- end }}
