{{- if .Values.demoRuntimeEncryption.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.runtimeEncryptionSecretName }}
  namespace: {{ include "weblogic-demo.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/part-of: weblogic-demo
type: Opaque
stringData:
  password: {{ .Values.demoRuntimeEncryption.password | quote }}
{{- end }}
