apiVersion: management.loft.sh/v1
kind: Team
metadata:
  name: weblogic-devs
spec:
  displayName: WebLogic Developers
  access:
    - name: loft-access
      subresources:
        - clusters
      teams:
        - weblogic-devs
      verbs:
        - get
        - bind
